USE Globalwonder;
insert into airport_lounges (code, lounge_type) values ('SHN', 'VIP');
insert into airport_lounges (code, lounge_type) values ('SHN', 'Business');
insert into airport_lounges (code, lounge_type) values ('MEP', 'First Class');
insert into airport_lounges (code, lounge_type) values ('MEP', 'Family');
insert into airport_lounges (code, lounge_type) values ('CEC', 'Premium');
insert into airport_lounges (code, lounge_type) values ('CEC', 'Members Only');
insert into airport_lounges (code, lounge_type) values ('YPL', 'International');
insert into airport_lounges (code, lounge_type) values ('YPL', 'Domestic');
insert into airport_lounges (code, lounge_type) values ('TKF', 'Transit');
insert into airport_lounges (code, lounge_type) values ('TKF', 'Relaxation');
insert into airport_lounges (code, lounge_type) values ('GAR', 'Spa');
insert into airport_lounges (code, lounge_type) values ('GAR', 'Conference');
insert into airport_lounges (code, lounge_type) values ('CNN', 'Gaming');
insert into airport_lounges (code, lounge_type) values ('CNN', 'Quiet Zone');
insert into airport_lounges (code, lounge_type) values ('MKS', 'VIP');
insert into airport_lounges (code, lounge_type) values ('MKS', 'Business');
insert into airport_lounges (code, lounge_type) values ('ZMG', 'First Class');
insert into airport_lounges (code, lounge_type) values ('ZMG', 'Family');
insert into airport_lounges (code, lounge_type) values ('ETH', 'Premium');
insert into airport_lounges (code, lounge_type) values ('ETH', 'Members Only');
insert into airport_lounges (code, lounge_type) values ('EIL', 'International');
insert into airport_lounges (code, lounge_type) values ('EIL', 'Domestic');
insert into airport_lounges (code, lounge_type) values ('BKA', 'Transit');
insert into airport_lounges (code, lounge_type) values ('BKA', 'Relaxation');
insert into airport_lounges (code, lounge_type) values ('NNU', 'Spa');
insert into airport_lounges (code, lounge_type) values ('NNU', 'Conference');
insert into airport_lounges (code, lounge_type) values ('0', 'Gaming');
insert into airport_lounges (code, lounge_type) values ('0', 'Quiet Zone');
insert into airport_lounges (code, lounge_type) values ('NDB', 'VIP');
insert into airport_lounges (code, lounge_type) values ('NDB', 'Business');
insert into airport_lounges (code, lounge_type) values ('MNI', 'First Class');
insert into airport_lounges (code, lounge_type) values ('MNI', 'Family');
insert into airport_lounges (code, lounge_type) values ('KIC', 'Premium');
insert into airport_lounges (code, lounge_type) values ('KIC', 'Members Only');
insert into airport_lounges (code, lounge_type) values ('MMC', 'International');
insert into airport_lounges (code, lounge_type) values ('MMC', 'Domestic');
insert into airport_lounges (code, lounge_type) values ('SID', 'Transit');
insert into airport_lounges (code, lounge_type) values ('SID', 'Relaxation');
insert into airport_lounges (code, lounge_type) values ('KDI', 'Spa');
insert into airport_lounges (code, lounge_type) values ('KDI', 'Conference');
insert into airport_lounges (code, lounge_type) values ('VNS', 'Gaming');
insert into airport_lounges (code, lounge_type) values ('VNS', 'Quiet Zone');
insert into airport_lounges (code, lounge_type) values ('LKP', 'VIP');
insert into airport_lounges (code, lounge_type) values ('LKP', 'Business');
insert into airport_lounges (code, lounge_type) values ('YSN', 'First Class');
insert into airport_lounges (code, lounge_type) values ('YSN', 'Family');
insert into airport_lounges (code, lounge_type) values ('CBD', 'Premium');
insert into airport_lounges (code, lounge_type) values ('CBD', 'Members Only');
insert into airport_lounges (code, lounge_type) values ('SBB', 'International');
insert into airport_lounges (code, lounge_type) values ('SBB', 'Domestic');
insert into airport_lounges (code, lounge_type) values ('HRC', 'Transit');
insert into airport_lounges (code, lounge_type) values ('HRC', 'Relaxation');
insert into airport_lounges (code, lounge_type) values ('NPE', 'Spa');
insert into airport_lounges (code, lounge_type) values ('NPE', 'Conference');
insert into airport_lounges (code, lounge_type) values ('QLR', 'Gaming');
insert into airport_lounges (code, lounge_type) values ('QLR', 'Quiet Zone');
insert into airport_lounges (code, lounge_type) values ('VIB', 'VIP');
insert into airport_lounges (code, lounge_type) values ('VIB', 'Business');
insert into airport_lounges (code, lounge_type) values ('VFA', 'First Class');
insert into airport_lounges (code, lounge_type) values ('VFA', 'Family');
insert into airport_lounges (code, lounge_type) values ('NKX', 'Premium');
insert into airport_lounges (code, lounge_type) values ('NKX', 'Members Only');
insert into airport_lounges (code, lounge_type) values ('WON', 'International');
insert into airport_lounges (code, lounge_type) values ('WON', 'Domestic');
insert into airport_lounges (code, lounge_type) values ('FKJ', 'Transit');
insert into airport_lounges (code, lounge_type) values ('FKJ', 'Relaxation');
insert into airport_lounges (code, lounge_type) values ('ITE', 'Spa');
insert into airport_lounges (code, lounge_type) values ('ITE', 'Conference');
insert into airport_lounges (code, lounge_type) values ('XXN', 'Gaming');
insert into airport_lounges (code, lounge_type) values ('XXN', 'Quiet Zone');
insert into airport_lounges (code, lounge_type) values ('HKA', 'VIP');
insert into airport_lounges (code, lounge_type) values ('HKA', 'Business');
insert into airport_lounges (code, lounge_type) values ('LIV', 'First Class');
insert into airport_lounges (code, lounge_type) values ('LIV', 'Family');
insert into airport_lounges (code, lounge_type) values ('APG', 'Premium');
insert into airport_lounges (code, lounge_type) values ('APG', 'Members Only');
insert into airport_lounges (code, lounge_type) values ('BWP', 'International');
insert into airport_lounges (code, lounge_type) values ('BWP', 'Domestic');
insert into airport_lounges (code, lounge_type) values ('ALS', 'Transit');
insert into airport_lounges (code, lounge_type) values ('ALS', 'Relaxation');
insert into airport_lounges (code, lounge_type) values ('SHN', 'Spa');
insert into airport_lounges (code, lounge_type) values ('SHN', 'Conference');
insert into airport_lounges (code, lounge_type) values ('MEP', 'Gaming');
insert into airport_lounges (code, lounge_type) values ('MEP', 'Quiet Zone');
insert into airport_lounges (code, lounge_type) values ('CEC', 'VIP');
insert into airport_lounges (code, lounge_type) values ('CEC', 'Business');
insert into airport_lounges (code, lounge_type) values ('YPL', 'First Class');
insert into airport_lounges (code, lounge_type) values ('YPL', 'Family');
insert into airport_lounges (code, lounge_type) values ('TKF', 'Premium');
insert into airport_lounges (code, lounge_type) values ('TKF', 'Members Only');
insert into airport_lounges (code, lounge_type) values ('GAR', 'International');
insert into airport_lounges (code, lounge_type) values ('GAR', 'Domestic');
insert into airport_lounges (code, lounge_type) values ('CNN', 'Transit');
insert into airport_lounges (code, lounge_type) values ('CNN', 'Relaxation');
insert into airport_lounges (code, lounge_type) values ('MKS', 'Spa');
insert into airport_lounges (code, lounge_type) values ('MKS', 'Conference');
insert into airport_lounges (code, lounge_type) values ('ZMG', 'Gaming');
insert into airport_lounges (code, lounge_type) values ('ZMG', 'Quiet Zone');
insert into airport_lounges (code, lounge_type) values ('ETH', 'VIP');
insert into airport_lounges (code, lounge_type) values ('ETH', 'Business');