USE Globalwonder;
delete from airports;
insert into airports (code, city) values ('SHN', 'Tikiw');
insert into airports (code, city) values ('MEP', 'Palmerston North');
insert into airports (code, city) values ('CEC', 'Lapai');
insert into airports (code, city) values ('YPL', 'Pawak');
insert into airports (code, city) values ('TKF', 'Pasco');
insert into airports (code, city) values ('GAR', 'Sewon');
insert into airports (code, city) values ('CNN', 'Trois-Rivières');
insert into airports (code, city) values ('MKS', 'Chowṉêy');
insert into airports (code, city) values ('ZMG', 'Kraljevo');
insert into airports (code, city) values ('ETH', 'Vaudreuil-Dorion');
insert into airports (code, city) values ('EIL', 'San Francisco');
insert into airports (code, city) values ('BKA', 'Taluksangay');
insert into airports (code, city) values ('NNU', 'Mantingantengah');
insert into airports (code, city) values ('0', 'Luofang');
insert into airports (code, city) values ('NDB', 'Jinka');
insert into airports (code, city) values ('MNI', 'Asempapan');
insert into airports (code, city) values ('KIC', 'El Progreso');
insert into airports (code, city) values ('MMC', 'Idrija');
insert into airports (code, city) values ('SID', 'New Iloilo');
insert into airports (code, city) values ('KDI', 'Maodian');
insert into airports (code, city) values ('VNS', 'Madison');
insert into airports (code, city) values ('LKP', 'Shahrak');
insert into airports (code, city) values ('YSN', 'Kokkári');
insert into airports (code, city) values ('CBD', 'Rumyantsevo');
insert into airports (code, city) values ('SBB', 'Kitcharao');
insert into airports (code, city) values ('HRC', 'Rio Negrinho');
insert into airports (code, city) values ('NPE', 'Stockholm');
insert into airports (code, city) values ('QLR', 'Baihua');
insert into airports (code, city) values ('VIB', 'Mafraq');
insert into airports (code, city) values ('VFA', 'Tarkastad');
insert into airports (code, city) values ('NKX', 'Dassun');
insert into airports (code, city) values ('WON', 'Pentéli');
insert into airports (code, city) values ('FKJ', 'Rungis');
insert into airports (code, city) values ('ITE', 'Cihideung Satu');
insert into airports (code, city) values ('XXN', 'Warri');
insert into airports (code, city) values ('HKA', 'Slobodskoy');
insert into airports (code, city) values ('LIV', 'Leonídio');
insert into airports (code, city) values ('APG', 'Banaybanay');
insert into airports (code, city) values ('BWP', 'Kalýves Polygýrou');
insert into airports (code, city) values ('ALS', 'Matanzas');

