insert into book_hotels (street_num, street, name, customer_id) values ('3793', 'Walton', 'Langosh Inc', 1);
insert into book_hotels (street_num, street, name, customer_id) values ('97', 'Almo', 'Jacobs, McCullough and Schulist', 67);
insert into book_hotels (street_num, street, name, customer_id) values ('46686', 'Nelson', 'Rath-Swift', 10);
insert into book_hotels (street_num, street, name, customer_id) values ('1', 'Melby', 'Johnson-Bahringer', 97);
insert into book_hotels (street_num, street, name, customer_id) values ('655', 'Mccormick', 'Cummerata Group', 7);
insert into book_hotels (street_num, street, name, customer_id) values ('2103', 'Blue Bill Park', 'Paucek-Metz', 70);
insert into book_hotels (street_num, street, name, customer_id) values ('63682', 'Boyd', 'Langosh, Windler and Pfeffer', 39);
insert into book_hotels (street_num, street, name, customer_id) values ('3', 'Straubel', 'D''Amore, Mann and Schmeler', 24);
insert into book_hotels (street_num, street, name, customer_id) values ('4', 'Orin', 'Parker and Sons', 14);
insert into book_hotels (street_num, street, name, customer_id) values ('757', 'Summer Ridge', 'Wiegand Group', 19);
insert into book_hotels (street_num, street, name, customer_id) values ('48361', 'Judy', 'Feeney LLC', 93);
insert into book_hotels (street_num, street, name, customer_id) values ('21067', 'Clarendon', 'Blick-Grimes', 41);
insert into book_hotels (street_num, street, name, customer_id) values ('64', 'Kings', 'Strosin, Jacobson and Corkery', 20);
insert into book_hotels (street_num, street, name, customer_id) values ('99665', 'Heath', 'Corwin, Cummings and Kuhlman', 13);
insert into book_hotels (street_num, street, name, customer_id) values ('7', 'Farmco', 'Kertzmann Inc', 68);
insert into book_hotels (street_num, street, name, customer_id) values ('14', 'Dryden', 'Maggio, Carter and Dickens', 49);
insert into book_hotels (street_num, street, name, customer_id) values ('4', 'Prentice', 'Windler LLC', 193);
insert into book_hotels (street_num, street, name, customer_id) values ('4', 'Manley', 'Koch Inc', 55);
insert into book_hotels (street_num, street, name, customer_id) values ('7', 'Rieder', 'Feeney, Bednar and Yundt', 33);
insert into book_hotels (street_num, street, name, customer_id) values ('7', 'Dwight', 'Kautzer-Greenholt', 100);
insert into book_hotels (street_num, street, name, customer_id) values ('2', 'Jenifer', 'Rippin LLC', 4);
insert into book_hotels (street_num, street, name, customer_id) values ('53157', 'Luster', 'Weissnat Inc', 114);
insert into book_hotels (street_num, street, name, customer_id) values ('956', 'Hauk', 'McKenzie, Wuckert and Simonis', 21);
insert into book_hotels (street_num, street, name, customer_id) values ('48704', 'Columbus', 'Wiza Inc', 26);
insert into book_hotels (street_num, street, name, customer_id) values ('7', 'Melvin', 'Kovacek-Collins', 16);
insert into book_hotels (street_num, street, name, customer_id) values ('6', 'Shelley', 'Green and Sons', 25);
insert into book_hotels (street_num, street, name, customer_id) values ('51', 'Tony', 'Dickens, Mueller and Lemke', 10000);
insert into book_hotels (street_num, street, name, customer_id) values ('11440', 'Prentice', 'Hills, Frami and Jacobi', 22);
insert into book_hotels (street_num, street, name, customer_id) values ('3137', 'Gulseth', 'Block, Predovic and Schulist', 86);
insert into book_hotels (street_num, street, name, customer_id) values ('65937', 'Gateway', 'Schultz, Macejkovic and Powlowski', 409);
insert into book_hotels (street_num, street, name, customer_id) values ('7665', 'Menomonie', 'Schulist-Reichert', 50);
insert into book_hotels (street_num, street, name, customer_id) values ('52241', 'Scott', 'Feeney, Daniel and Dach', 12);
insert into book_hotels (street_num, street, name, customer_id) values ('56473', 'Anthes', 'Hudson-Barton', 11);
insert into book_hotels (street_num, street, name, customer_id) values ('009', 'Village Green', 'Ratke, Braun and Schuppe', 73);
insert into book_hotels (street_num, street, name, customer_id) values ('0', 'Grasskamp', 'Kreiger-Gerlach', 91);

