insert into cars (company_name, license_plate, model, available, capacity) values ('Acme Motors', 'ABC123', 'Toyota Corolla', true, 5);
insert into cars (company_name, license_plate, model, available, capacity) values ('Acme Motors', 'DEF456', 'Honda Civic', true, 5);
insert into cars (company_name, license_plate, model, available, capacity) values ('Acme Motors', 'GHI789', 'Ford Focus', true, 5);
insert into cars (company_name, license_plate, model, available, capacity) values ('Acme Motors', 'JKL012', 'Chevrolet Malibu', true, 5);
insert into cars (company_name, license_plate, model, available, capacity) values ('Acme Motors', 'MNO345', 'Nissan Altima', true, 5);
insert into cars (company_name, license_plate, model, available, capacity) values ('Acme Motors', 'PQR678', 'Volkswagen Jetta', true, 5);
insert into cars (company_name, license_plate, model, available, capacity) values ('Starlight Automotive', 'STL001', 'Toyota Camry', true, 5);
insert into cars (company_name, license_plate, model, available, capacity) values ('Starlight Automotive', 'STL002', 'Honda Accord', true, 5);
insert into cars (company_name, license_plate, model, available, capacity) values ('Starlight Automotive', 'STL003', 'Ford Fusion', true, 5);
insert into cars (company_name, license_plate, model, available, capacity) values ('Starlight Automotive', 'STL004', 'Chevrolet Impala', true, 5);
insert into cars (company_name, license_plate, model, available, capacity) values ('Starlight Automotive', 'STL005', 'Nissan Maxima', true, 5);
insert into cars (company_name, license_plate, model, available, capacity) values ('Starlight Automotive', 'STL006', 'Volkswagen Passat', true, 5);
insert into cars (company_name, license_plate, model, available, capacity) values ('Thunderbolt Cars', 'THB001', 'Toyota Yaris', true, 5);
insert into cars (company_name, license_plate, model, available, capacity) values ('Thunderbolt Cars', 'THB002', 'Honda Fit', true, 5);
insert into cars (company_name, license_plate, model, available, capacity) values ('Thunderbolt Cars', 'THB003', 'Ford Fiesta', true, 5);
insert into cars (company_name, license_plate, model, available, capacity) values ('Thunderbolt Cars', 'THB004', 'Chevrolet Spark', true, 5);
insert into cars (company_name, license_plate, model, available, capacity) values ('Thunderbolt Cars', 'THB005', 'Nissan Versa', true, 5);
insert into cars (company_name, license_plate, model, available, capacity) values ('Thunderbolt Cars', 'THB006', 'Volkswagen Golf', true, 5);
insert into cars (company_name, license_plate, model, available, capacity) values ('Prestige Motors', 'PRS001', 'BMW 3 Series', true, 5);
insert into cars (company_name, license_plate, model, available, capacity) values ('Prestige Motors', 'PRS002', 'Mercedes-Benz C-Class', true, 5);
insert into cars (company_name, license_plate, model, available, capacity) values ('Prestige Motors', 'PRS003', 'Audi A4', true, 5);
insert into cars (company_name, license_plate, model, available, capacity) values ('Prestige Motors', 'PRS004', 'Lexus ES', true, 5);
insert into cars (company_name, license_plate, model, available, capacity) values ('Prestige Motors', 'PRS005', 'Infiniti Q50', true, 5);
insert into cars (company_name, license_plate, model, available, capacity) values ('Prestige Motors', 'PRS006', 'Jaguar XE', true, 5);
insert into cars (company_name, license_plate, model, available, capacity) values ('Golden Wheels', 'GLD001', 'Hyundai Elantra', true, 5);
insert into cars (company_name, license_plate, model, available, capacity) values ('Golden Wheels', 'GLD002', 'Kia Forte', true, 5);
insert into cars (company_name, license_plate, model, available, capacity) values ('Golden Wheels', 'GLD003', 'Mazda3', true, 5);
insert into cars (company_name, license_plate, model, available, capacity) values ('Golden Wheels', 'GLD004', 'Subaru Impreza', true, 5);
insert into cars (company_name, license_plate, model, available, capacity) values ('Golden Wheels', 'GLD005', 'Mitsubishi Lancer', true, 5);
insert into cars (company_name, license_plate, model, available, capacity) values ('Golden Wheels', 'GLD006', 'Chrysler 200', true, 5);
insert into cars (company_name, license_plate, model, available, capacity) values ('Velocity Autos', 'VLC001', 'Toyota Prius', true, 5);
insert into cars (company_name, license_plate, model, available, capacity) values ('Velocity Autos', 'VLC002', 'Honda Insight', true, 5);
insert into cars (company_name, license_plate, model, available, capacity) values ('Velocity Autos', 'VLC003', 'Ford C-Max', true, 5);
insert into cars (company_name, license_plate, model, available, capacity) values ('Velocity Autos', 'VLC004', 'Chevrolet Volt', true, 5);
insert into cars (company_name, license_plate, model, available, capacity) values ('Velocity Autos', 'VLC005', 'Nissan Leaf', true, 5);
insert into cars (company_name, license_plate, model, available, capacity) values ('Velocity Autos', 'VLC006', 'BMW i3', true, 5);
insert into cars (company_name, license_plate, model, available, capacity) values ('Silver Arrow Vehicles', 'SLV001', 'Tesla Model S', true, 5);
insert into cars (company_name, license_plate, model, available, capacity) values ('Silver Arrow Vehicles', 'SLV002', 'Tesla Model 3', true, 5);
insert into cars (company_name, license_plate, model, available, capacity) values ('Silver Arrow Vehicles', 'SLV003', 'Tesla Model X', true, 5);
insert into cars (company_name, license_plate, model, available, capacity) values ('Silver Arrow Vehicles', 'SLV004', 'Tesla Model Y', true, 5);
insert into cars (company_name, license_plate, model, available, capacity) values ('Silver Arrow Vehicles', 'SLV005', 'Porsche Taycan', true, 5);
insert into cars (company_name, license_plate, model, available, capacity) values ('Silver Arrow Vehicles', 'SLV006', 'Audi e-tron', true, 5);
insert into cars (company_name, license_plate, model, available, capacity) values ('Royal Motors', 'RYL001', 'Rolls-Royce Ghost', true, 5);
insert into cars (company_name, license_plate, model, available, capacity) values ('Royal Motors', 'RYL002', 'Bentley Flying Spur', true, 5);
insert into cars (company_name, license_plate, model, available, capacity) values ('Royal Motors', 'RYL003', 'Mercedes-Maybach S-Class', true, 5);
insert into cars (company_name, license_plate, model, available, capacity) values ('Royal Motors', 'RYL004', 'BMW 7 Series', true, 5);
insert into cars (company_name, license_plate, model, available, capacity) values ('Royal Motors', 'RYL005', 'Audi A8', true, 5);
insert into cars (company_name, license_plate, model, available, capacity) values ('Royal Motors', 'RYL006', 'Lexus LS', true, 5);