USE Globalwonder;
INSERT INTO flight_menu (flight_id, drinks, dessert, main_course) VALUES
(1, 'Water, Juice', 'Chocolate Cake', 'Grilled Chicken with Rice'),
(2, 'Soda, Wine', 'Cheesecake', 'Beef Steak with Mashed Potatoes'),
(3, 'Orange Juice, Tea', 'Fruit Salad', 'Pasta Alfredo'),
(4, 'Water, Wine', 'Tiramisu', 'Salmon with Quinoa'),
(5, 'Soda, Beer', 'Apple Pie', 'Vegetable Stir-Fry'),
(6, 'Cocktail, Champagne', 'Tart', 'Lobster with Risotto'),
(7, 'Iced Tea, Juice', 'Ice Cream', 'Vegetarian Lasagna'),
(8, 'Coffee, Soft Drinks', 'Brownie', 'BBQ Ribs with Coleslaw'),
(9, 'Wine, Vodka', 'Pudding', 'Seafood Paella'),
(10, 'Soda, Water', 'Mousse', 'Mushroom Risotto'),
(11, 'Beer, Whiskey', 'Fruit Tart', 'Eggplant Parmesan'),
(12, 'Sparkling Water, Juice', 'Tiramisu', 'Chicken Caesar Salad'),
(13, 'Tequila, Margarita', 'Cheesecake', 'Beef Burger with Fries'),
(14, 'Wine, Soft Drinks', 'Fruit Salad', 'Grilled Salmon with Couscous'),
(15, 'Cocktail, Champagne', 'Chocolate Mousse', 'Vegetable Curry with Rice'),
(16, 'Beer, Soda', 'Ice Cream', 'Shrimp Scampi'),
(17, 'Water, Coffee', 'Apple Pie', 'Steak Sandwich'),
(18, 'Soda, Wine', 'Tart', 'Chicken Tikka Masala'),
(19, 'Whiskey, Soft Drinks', 'Pudding', 'Spaghetti Carbonara'),
(20, 'Wine, Juice', 'Mousse', 'Vegetable Pad Thai'),
(21, 'Beer, Cocktail', 'Fruit Tart', 'Caprese Salad'),
(22, 'Vodka, Orange Juice', 'Tiramisu', 'Sushi Platter'),
(23, 'Soda, Wine', 'Cheesecake', 'Stuffed Bell Peppers'),
(24, 'Water, Beer', 'Fruit Salad', 'Pork Chops with Applesauce'),
(25, 'Coffee, Tea', 'Brownie', 'Tofu Stir-Fry'),
(26, 'Soft Drinks, Wine', 'Pudding', 'Beef Stroganoff'),
(27, 'Juice, Sparkling Water', 'Mousse', 'Vegetable Risotto'),
(28, 'Beer, Cocktail', 'Ice Cream', 'Chicken Quesadilla'),
(29, 'Soda, Wine', 'Apple Pie', 'Grilled Cheese Sandwich'),
(30, 'Water, Juice', 'Tart', 'Vegetarian Chili');
INSERT INTO flight_menu (flight_id, drinks, dessert, main_course) VALUES
(1, 'Water', 'Chocolate Cake', 'Grilled Chicken with Rice'),
(2, 'Soda', 'Cheesecake', 'Beef Steak with Mashed Potatoes'),
(3, 'Orange Juice', 'Fruit Salad', 'Pasta Alfredo'),
(4, 'Water', 'Tiramisu', 'Salmon with Quinoa'),
(5, 'Soda', 'Apple Pie', 'Vegetable Stir-Fry'),
(6, 'Cocktail', 'Tart', 'Lobster with Risotto'),
(7, 'Iced Tea', 'Ice Cream', 'Vegetarian Lasagna'),
(8, 'Coffee', 'Brownie', 'BBQ Ribs with Coleslaw'),
(9, 'Wine', 'Pudding', 'Seafood Paella'),
(10, 'Water', 'Mousse', 'Mushroom Risotto'),
(11, 'Beer', 'Fruit Tart', 'Eggplant Parmesan'),
(12, 'Sparkling Water', 'Tiramisu', 'Chicken Caesar Salad'),
(13, 'Tequila', 'Cheesecake', 'Beef Burger with Fries'),
(14, 'Soft Drinks', 'Fruit Salad', 'Grilled Salmon with Couscous'),
(15, 'Champagne', 'Chocolate Mousse', 'Vegetable Curry with Rice'),
(16, 'Soda', 'Ice Cream', 'Shrimp Scampi'),
(17, 'Water', 'Apple Pie', 'Steak Sandwich'),
(18, 'Wine', 'Tart', 'Chicken Tikka Masala'),
(19, 'Whiskey', 'Pudding', 'Spaghetti Carbonara'),
(20, 'Juice', 'Mousse', 'Vegetable Pad Thai'),
(21, 'Cocktail', 'Fruit Tart', 'Caprese Salad'),
(22, 'Vodka', 'Tiramisu', 'Sushi Platter'),
(23, 'Orange Juice', 'Cheesecake', 'Stuffed Bell Peppers'),
(24, 'Beer', 'Fruit Salad', 'Pork Chops with Applesauce'),
(25, 'Tea', 'Brownie', 'Tofu Stir-Fry'),
(26, 'Soft Drinks', 'Pudding', 'Beef Stroganoff'),
(27, 'Sparkling Water', 'Mousse', 'Vegetable Risotto'),
(28, 'Cocktail', 'Ice Cream', 'Chicken Quesadilla'),
(29, 'Wine', 'Apple Pie', 'Grilled Cheese Sandwich'),
(30, 'Water', 'Tart', 'Vegetarian Chili');

