USE Globalwonder;
insert into hotels (street_num, street, name, ranking) values ('3793', 'Walton', 'Langosh Inc', 2.9);
insert into hotels (street_num, street, name, ranking) values ('97', 'Almo', 'Jacobs, McCullough and Schulist', 5.6);
insert into hotels (street_num, street, name, ranking) values ('46686', 'Nelson', 'Rath-Swift', 7.2);
insert into hotels (street_num, street, name, ranking) values ('1', 'Melby', 'Johnson-Bahringer', 8.5);
insert into hotels (street_num, street, name, ranking) values ('655', 'Mccormick', 'Cummerata Group', 7.5);
insert into hotels (street_num, street, name, ranking) values ('2103', 'Blue Bill Park', 'Paucek-Metz', 4.8);
insert into hotels (street_num, street, name, ranking) values ('63682', 'Boyd', 'Langosh, Windler and Pfeffer', 9.8);
insert into hotels (street_num, street, name, ranking) values ('3', 'Straubel', 'D''Amore, Mann and Schmeler', 3.6);
insert into hotels (street_num, street, name, ranking) values ('4', 'Orin', 'Parker and Sons', 8.3);
insert into hotels (street_num, street, name, ranking) values ('757', 'Summer Ridge', 'Wiegand Group', 3.1);
insert into hotels (street_num, street, name, ranking) values ('48361', 'Judy', 'Feeney LLC', 0.0);
insert into hotels (street_num, street, name, ranking) values ('21067', 'Clarendon', 'Blick-Grimes', 7.8);
insert into hotels (street_num, street, name, ranking) values ('64', 'Kings', 'Strosin, Jacobson and Corkery', 7.9);
insert into hotels (street_num, street, name, ranking) values ('99665', 'Heath', 'Corwin, Cummings and Kuhlman', 9.9);
insert into hotels (street_num, street, name, ranking) values ('7', 'Farmco', 'Kertzmann Inc', 4.3);
insert into hotels (street_num, street, name, ranking) values ('14', 'Dryden', 'Maggio, Carter and Dickens', 5.8);
insert into hotels (street_num, street, name, ranking) values ('4', 'Prentice', 'Windler LLC', 7.1);
insert into hotels (street_num, street, name, ranking) values ('4', 'Manley', 'Koch Inc', 6.7);
insert into hotels (street_num, street, name, ranking) values ('7', 'Rieder', 'Feeney, Bednar and Yundt', 0.7);
insert into hotels (street_num, street, name, ranking) values ('7', 'Dwight', 'Kautzer-Greenholt', 8.2);
insert into hotels (street_num, street, name, ranking) values ('2', 'Jenifer', 'Rippin LLC', 6.1);
insert into hotels (street_num, street, name, ranking) values ('53157', 'Luster', 'Weissnat Inc', 7.8);
insert into hotels (street_num, street, name, ranking) values ('956', 'Hauk', 'McKenzie, Wuckert and Simonis', 6.6);
insert into hotels (street_num, street, name, ranking) values ('48704', 'Columbus', 'Wiza Inc', 7.4);
insert into hotels (street_num, street, name, ranking) values ('7', 'Melvin', 'Kovacek-Collins', 2.9);
insert into hotels (street_num, street, name, ranking) values ('6', 'Shelley', 'Green and Sons', 1.0);
insert into hotels (street_num, street, name, ranking) values ('51', 'Tony', 'Dickens, Mueller and Lemke', 1.2);
insert into hotels (street_num, street, name, ranking) values ('11440', 'Prentice', 'Hills, Frami and Jacobi', 2.0);
insert into hotels (street_num, street, name, ranking) values ('3137', 'Gulseth', 'Block, Predovic and Schulist', 3.9);
insert into hotels (street_num, street, name, ranking) values ('65937', 'Gateway', 'Schultz, Macejkovic and Powlowski', 2.5);
insert into hotels (street_num, street, name, ranking) values ('7665', 'Menomonie', 'Schulist-Reichert', 8.2);
insert into hotels (street_num, street, name, ranking) values ('52241', 'Scott', 'Feeney, Daniel and Dach', 0.4);
insert into hotels (street_num, street, name, ranking) values ('56473', 'Anthes', 'Hudson-Barton', 2.7);
insert into hotels (street_num, street, name, ranking) values ('009', 'Village Green', 'Ratke, Braun and Schuppe', 9.4);
insert into hotels (street_num, street, name, ranking) values ('0', 'Grasskamp', 'Kreiger-Gerlach', 1.3);
