USE Globalwonder;
-- Inserting data into rent_car table
INSERT INTO rent_car (company_name, customer_id) VALUES
('Acme Motors', 1),
('Starlight Automotive', 67),
('Thunderbolt Cars', 10),
('Prestige Motors', 97),
('Golden Wheels', 7),
('Velocity Autos', 70),
('Silver Arrow Vehicles', 39),
('Royal Motors', 24),
('Elite Automotive', 14),
('Sunrise Cars', 19),
('Acme Motors', 93),
('Starlight Automotive', 41),
('Thunderbolt Cars', 20),
('Prestige Motors', 13),
('Golden Wheels', 68),
('Velocity Autos', 49),
('Silver Arrow Vehicles', 193),
('Royal Motors', 55),
('Elite Automotive', 33),
('Sunrise Cars', 100),
('Acme Motors', 4),
('Starlight Automotive', 114),
('Thunderbolt Cars', 21),
('Prestige Motors', 26),
('Golden Wheels', 16),
('Velocity Autos', 25),
('Silver Arrow Vehicles', 10000),
('Royal Motors', 22),
('Elite Automotive', 86),
('Sunrise Cars', 409),
('Acme Motors', 50),
('Starlight Automotive', 12),
('Thunderbolt Cars', 11),
('Prestige Motors', 73),
('Golden Wheels', 91),
('Velocity Autos', 45),
('Silver Arrow Vehicles', 89),
('Royal Motors', 72),
('Elite Automotive', 3),
('Sunrise Cars', 119),
('Acme Motors', 1111),
('Starlight Automotive', 9),
('Thunderbolt Cars', 36),
('Prestige Motors', 701),
('Golden Wheels', 702),
('Velocity Autos', 94),
('Silver Arrow Vehicles', 891),
('Royal Motors', 362),
('Elite Automotive', 681),
('Sunrise Cars', 7011),
('Acme Motors', 54),
('Starlight Automotive', 81),
('Thunderbolt Cars', 311),
('Prestige Motors', 57),
('Golden Wheels', 721),
('Velocity Autos', 451),
('Silver Arrow Vehicles', 79),
('Royal Motors', 28),
('Elite Automotive', 32),
('Sunrise Cars', 52);
-- Inserting data into rent_car table
INSERT INTO rent_car (company_name, customer_id) VALUES
('Acme Motors', 7),
('Starlight Automotive', 70),
('Thunderbolt Cars', 39),
('Prestige Motors', 24),
('Golden Wheels', 14),
('Velocity Autos', 19),
('Silver Arrow Vehicles', 93),
('Royal Motors', 41),
('Elite Automotive', 20),
('Sunrise Cars', 68),
('Acme Motors', 49),
('Starlight Automotive', 193),
('Thunderbolt Cars', 55),
('Prestige Motors', 33),
('Golden Wheels', 100),
('Velocity Autos', 4),
('Silver Arrow Vehicles', 114),
('Royal Motors', 21),
('Elite Automotive', 26),
('Sunrise Cars', 16),
('Acme Motors', 10000),
('Starlight Automotive', 22),
('Thunderbolt Cars', 86),
('Prestige Motors', 409),
('Golden Wheels', 50),
('Velocity Autos', 12),
('Silver Arrow Vehicles', 11),
('Royal Motors', 73),
('Elite Automotive', 91),
('Sunrise Cars', 45),
('Acme Motors', 89),
('Starlight Automotive', 72),
('Thunderbolt Cars', 3),
('Prestige Motors', 119),
('Golden Wheels', 1111),
('Velocity Autos', 9),
('Silver Arrow Vehicles', 36),
('Royal Motors', 701),
('Elite Automotive', 702),
('Sunrise Cars', 94),
('Acme Motors', 891),
('Starlight Automotive', 362),
('Thunderbolt Cars', 681),
('Prestige Motors', 7011),
('Golden Wheels', 54),
('Velocity Autos', 81),
('Silver Arrow Vehicles', 311),
('Royal Motors', 57),
('Elite Automotive', 721),
('Sunrise Cars', 451),
('Acme Motors', 79),
('Starlight Automotive', 28),
('Thunderbolt Cars', 32),
('Prestige Motors', 52),
('Golden Wheels', 70),
('Velocity Autos', 39),
('Silver Arrow Vehicles', 24),
('Royal Motors', 14),
('Elite Automotive', 19),
('Sunrise Cars', 93),
('Acme Motors', 41),
('Starlight Automotive', 20),
('Thunderbolt Cars', 68),
('Prestige Motors', 49),
('Golden Wheels', 193),
('Velocity Autos', 55),
('Silver Arrow Vehicles', 33),
('Royal Motors', 100),
('Elite Automotive', 4),
('Sunrise Cars', 114),
('Acme Motors', 21),
('Starlight Automotive', 10000),
('Thunderbolt Cars', 22),
('Prestige Motors', 86),
('Golden Wheels', 409),
('Velocity Autos', 50),
('Silver Arrow Vehicles', 12),
('Royal Motors', 11),
('Elite Automotive', 73),
('Sunrise Cars', 91),
('Acme Motors', 45),
('Starlight Automotive', 89),
('Thunderbolt Cars', 72),
('Prestige Motors', 3),
('Golden Wheels', 119),
('Velocity Autos', 1111),
('Silver Arrow Vehicles', 9),
('Royal Motors', 36),
('Elite Automotive', 701),
('Sunrise Cars', 702),
('Acme Motors', 94),
('Starlight Automotive', 891),
('Thunderbolt Cars', 362),
('Prestige Motors', 681),
('Golden Wheels', 7011),
('Velocity Autos', 54),
('Silver Arrow Vehicles', 81),
('Royal Motors', 311),
('Elite Automotive', 57),
('Sunrise Cars', 721),
('Acme Motors', 451),
('Starlight Automotive', 79),
('Thunderbolt Cars', 28),
('Prestige Motors', 32),
('Golden Wheels', 52);