insert into rent_car_company (company_name, rating) values ('Acme Motors', 7.19);
insert into rent_car_company (company_name, rating) values ('Starlight Automotive', 3.3);
insert into rent_car_company (company_name, rating) values ('Thunderbolt Cars', 2.86);
insert into rent_car_company (company_name, rating) values ('Prestige Motors', 9.47);
insert into rent_car_company (company_name, rating) values ('Golden Wheels', 1.48);
insert into rent_car_company (company_name, rating) values ('Velocity Autos', 4.41);
insert into rent_car_company (company_name, rating) values ('Silver Arrow Vehicles', 9.27);
insert into rent_car_company (company_name, rating) values ('Royal Motors', 6.27);
insert into rent_car_company (company_name, rating) values ('Elite Automotive', 1.77);
insert into rent_car_company (company_name, rating) values ('Sunrise Cars', 5.77);
insert into rent_car_company (company_name, rating) values ('Acme cccs', 3.53);
insert into rent_car_company (company_name, rating) values ('Stlight Ative', 1.78);
insert into rent_car_company (company_name, rating) values ('Thunolt Cars', 1.62);
insert into rent_car_company (company_name, rating) values ('Prese Motors', 8.29);
insert into rent_car_company (company_name, rating) values ('Golden Whls', 6.37);
insert into rent_car_company (company_name, rating) values ('Vely Autos', 6.99);
insert into rent_car_company (company_name, rating) values ('Silve Vehicles', 2.48);
insert into rent_car_company (company_name, rating) values ('RoyMotrs', 1.31);
insert into rent_car_company (company_name, rating) values ('Ele Autotive', 3.17);
insert into rent_car_company (company_name, rating) values ('Sunr Cars', 8.14);
insert into rent_car_company (company_name, rating) values ('AcmMors', 3.56);
insert into rent_car_company (company_name, rating) values ('ight Automotive', 4.56);
insert into rent_car_company (company_name, rating) values ('Thundeolt Cars', 4.83);
insert into rent_car_company (company_name, rating) values ('Presge Motors', 3.5);
insert into rent_car_company (company_name, rating) values ('Golden Whes', 1.82);
insert into rent_car_company (company_name, rating) values ('city Autos', 7.26);
insert into rent_car_company (company_name, rating) values ('Silver Arr icles', 8.3);
insert into rent_car_company (company_name, rating) values ('RoyMors', 2.64);
insert into rent_car_company (company_name, rating) values ('Elite Auotive', 3.92);
insert into rent_car_company (company_name, rating) values ('Sunrie Cars', 9.06);
